# name: CI/CD - Aedion Server

# on:
#   push:
#     branches:
#       - development   # Change if you want another branch to trigger

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v4

#       - name: Deploy to EC2 and rebuild
#         uses: appleboy/ssh-action@v1.0.0
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USER }}
#           key: ${{ secrets.EC2_KEY }}
#           script: |
#             cd ~/adeonai_server  
#             git reset --hard
#             git pull origin development
            
#             sudo docker-compose down -v

#             sudo docker system prune -a --volumes -f

#             sudo docker-compose build --no-cache

#             sudo docker-compose up -d
